#include "compendium_enrichment.h"
#include "compendium_enrichment_sql.h"
#include "compendium_enrichment_mame_common.h"
#include "../core/constants/system_ids.h"

#include <QDebug>
#include <QFile>
#include <QHash>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QXmlStreamReader>

using namespace Remus;
using namespace CompendiumEnrichmentSql;
using namespace CompendiumEnrichmentMame;

namespace {

struct MachineInfo {
    QString manufacturer;
    int year = 0;
    int players = 0;
};

// Stream-parse a MAME listxml file (generated by `mame -listxml`) and return
// a map of romname → MachineInfo for runnable, non-device machines only.
// Clones are included — they share manufacturer/year with the parent and need
// their own facts in the database.
QHash<QString, MachineInfo> parseMameListXml(const QString &path, QString &error) {
    QHash<QString, MachineInfo> index;
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        error = QStringLiteral("Cannot open listxml: %1").arg(file.errorString());
        return index;
    }

    QXmlStreamReader xml(&file);
    while (!xml.atEnd() && !xml.hasError()) {
        xml.readNext();
        if (xml.tokenType() != QXmlStreamReader::StartElement || xml.name() != QLatin1String("machine"))
            continue;

        const QXmlStreamAttributes attrs = xml.attributes();
        // Skip device entries (sound chips, CPUs) and non-runnable BIOS/sample sets.
        if (attrs.value(QLatin1String("isdevice")) == QLatin1String("yes")
            || attrs.value(QLatin1String("runnable")) == QLatin1String("no")) {
            xml.skipCurrentElement();
            continue;
        }
        const QString romName = attrs.value(QLatin1String("name")).toString();
        if (romName.isEmpty()) {
            xml.skipCurrentElement();
            continue;
        }

        MachineInfo info;
        while (xml.readNext()) {
            if (xml.tokenType() == QXmlStreamReader::EndElement && xml.name() == QLatin1String("machine"))
                break;
            if (xml.tokenType() != QXmlStreamReader::StartElement)
                continue;
            if (xml.name() == QLatin1String("year")) {
                const QString yearStr = xml.readElementText().trimmed();
                bool ok = false;
                const int y = yearStr.toInt(&ok);
                if (ok && y >= 1970 && y <= 2030)
                    info.year = y;
            } else if (xml.name() == QLatin1String("manufacturer")) {
                info.manufacturer = xml.readElementText().trimmed();
            } else if (xml.name() == QLatin1String("input")) {
                const QString playersStr = xml.attributes().value(QLatin1String("players")).toString();
                bool ok = false;
                const int p = playersStr.toInt(&ok);
                if (ok && p >= 1 && p <= 16)
                    info.players = p;
            } else {
                xml.skipCurrentElement();
            }
        }

        if (!index.contains(romName))
            index.insert(romName, info);
    }

    if (xml.hasError()) {
        error = QStringLiteral("XML parse error in listxml: %1").arg(xml.errorString());
        return { };
    }

    return index;
}

} // namespace

namespace CompendiumEnrichment {

bool enrichFromMameListXml(
    QSqlDatabase &database, const QString &listxmlPath, int &gamesEnriched, int &factsInserted, QString &error) {
    gamesEnriched = 0;
    factsInserted = 0;

    QHash<QString, MachineInfo> machines = parseMameListXml(listxmlPath, error);
    if (machines.isEmpty()) {
        if (!error.isEmpty())
            return false;
        qInfo() << "[MAME-listxml] No entries parsed — pass skipped";
        return true;
    }

    qInfo().noquote() << QStringLiteral("[MAME-listxml] Parsed %1 machine entries from listxml").arg(machines.size());

    const QString snapshotId = QStringLiteral("mame-listxml-bulk");
    if (!upsertEnrichmentSource(database,
            SourceSpec {
                QStringLiteral("mame-listxml"),
                QStringLiteral("MAME listxml"),
                QStringLiteral("static-file"),
                QStringLiteral("https://github.com/mamedev/mame"),
                /*attributionRequired=*/false,
                /*priority=*/50,
                QString(),
            },
            SnapshotSpec {
                snapshotId,
                QStringLiteral("MAME listxml machine enrichment"),
            },
            error))
        return false;

    QSqlQuery updateQ(database);
    updateQ.prepare(QStringLiteral("UPDATE games SET "
                                   "developer    = COALESCE(NULLIF(developer, ''), ?), "
                                   "publisher    = COALESCE(NULLIF(publisher, ''), ?), "
                                   "release_year = COALESCE(release_year, ?), "
                                   "players_max  = COALESCE(players_max, ?) "
                                   "WHERE game_id = ?"));

    QSqlQuery factQ(database);
    factQ.prepare(QStringLiteral("INSERT INTO game_facts "
                                 "(game_id, field_name, field_value, value_type, source_id, snapshot_id, "
                                 "source_priority, confidence) "
                                 "VALUES (?, ?, ?, ?, ?, ?, ?, ?)"));

    QSqlQuery delQ(database);
    delQ.prepare(QStringLiteral("DELETE FROM game_facts WHERE game_id = ? AND field_name = ? AND source_id = ?"));

    const FactInsertSpec factSpec {
        QStringLiteral("mame-listxml"),
        snapshotId,
        50,
        0.85,
    };

    if (!bulkClearSourceFactBlockers(database, factSpec.sourceId, error))
        return false;

    const QSet<QString> skipGameIds = loadGamesWithMinSourceFieldFacts(database, factSpec.sourceId, 2, error);
    if (!error.isEmpty())
        return false;

    FactReplaceQueries replaceQueries(database);
    EnrichmentBatchWriter batchWriter(database);

    // Only query arcade games that are still missing at least one of the fields
    // this enricher provides. Games fully populated by a higher-priority source
    // still receive updated game_facts (via DELETE+INSERT) for resolver accuracy,
    // but the games table COALESCE update will be a no-op for them.
    QSqlQuery gamesQ(database);
    if (!gamesQ.exec(QStringLiteral("SELECT g.game_id, g.canonical_title, gn.name_text "
                                    "FROM games g "
                                    "LEFT JOIN game_names gn ON gn.game_id = g.game_id "
                                    "WHERE g.system_id = %1 "
                                    "  AND (g.developer IS NULL OR TRIM(g.developer) = '' "
                                    "    OR g.publisher IS NULL OR TRIM(g.publisher) = '' "
                                    "    OR g.release_year IS NULL "
                                    "    OR g.players_max IS NULL) "
                                    "ORDER BY g.game_id")
                .arg(Constants::Systems::ID_ARCADE))) {
        error = QStringLiteral("Query arcade games for MAME listxml: %1").arg(gamesQ.lastError().text());
        return false;
    }

    QString currentGameId;
    QString canonicalTitle;
    QStringList romNameCandidates;

    auto applyMachineInfo = [&](const MachineInfo &info) -> bool {
        updateQ.bindValue(0, nullableText(info.manufacturer));
        updateQ.bindValue(1, nullableText(info.manufacturer));
        updateQ.bindValue(2, nullableInt(info.year));
        updateQ.bindValue(3, nullableInt(info.players));
        updateQ.bindValue(4, currentGameId);
        if (!execPrepared(updateQ, error, QStringLiteral("Update MAME listxml")))
            return false;
        if (updateQ.numRowsAffected() > 0)
            ++gamesEnriched;

        bool inserted = false;

        if (!info.manufacturer.isEmpty()) {
            if (!insertGameFact(replaceQueries, delQ, factQ, factSpec, currentGameId, QStringLiteral("developer"), info.manufacturer,
                    QStringLiteral("text"), error, QStringLiteral("mame-listxml"), &inserted))
                return false;
            if (inserted)
                ++factsInserted;

            inserted = false;
            if (!insertGameFact(replaceQueries, delQ, factQ, factSpec, currentGameId, QStringLiteral("publisher"), info.manufacturer,
                    QStringLiteral("text"), error, QStringLiteral("mame-listxml"), &inserted))
                return false;
            if (inserted)
                ++factsInserted;
        }

        if (info.year > 0) {
            inserted = false;
            if (!insertGameFact(replaceQueries, delQ, factQ, factSpec, currentGameId, QStringLiteral("release_year"),
                    QString::number(info.year), QStringLiteral("int"), error, QStringLiteral("mame-listxml"),
                    &inserted))
                return false;
            if (inserted)
                ++factsInserted;
        }

        if (info.players > 0) {
            inserted = false;
            if (!insertGameFact(replaceQueries, delQ, factQ, factSpec, currentGameId, QStringLiteral("players_max"),
                    QString::number(info.players), QStringLiteral("int"), error, QStringLiteral("mame-listxml"),
                    &inserted))
                return false;
            if (inserted)
                ++factsInserted;
        }
        return true;
    };

    auto flushCurrentGame = [&]() -> bool {
        if (currentGameId.isEmpty())
            return true;
        if (skipGameIds.contains(currentGameId)) {
            currentGameId.clear();
            canonicalTitle.clear();
            romNameCandidates.clear();
            return batchWriter.onGameProcessed(error);
        }
        for (const QString &candidate : romNameCandidates) {
            const auto it = machines.constFind(candidate);
            if (it == machines.cend())
                continue;
            const bool ok = applyMachineInfo(it.value());
            currentGameId.clear();
            canonicalTitle.clear();
            romNameCandidates.clear();
            if (!ok)
                return false;
            return batchWriter.onGameProcessed(error);
        }
        currentGameId.clear();
        canonicalTitle.clear();
        romNameCandidates.clear();
        return batchWriter.onGameProcessed(error);
    };

    while (gamesQ.next()) {
        const QString gameId = gamesQ.value(0).toString();
        const QString title = gamesQ.value(1).toString().trimmed();
        const QString alias = gamesQ.value(2).toString().trimmed();

        if (gameId != currentGameId) {
            if (!flushCurrentGame())
                return false;
            currentGameId = gameId;
            canonicalTitle = title;
            romNameCandidates.clear();
            appendRomNameCandidate(romNameCandidates, title);
        }

        appendRomNameCandidate(romNameCandidates, alias);
    }
    if (!flushCurrentGame())
        return false;

    if (!batchWriter.finish(error))
        return false;

    qInfo().noquote()
        << QStringLiteral("[MAME-listxml] +%1 games enriched, +%2 facts").arg(gamesEnriched).arg(factsInserted);
    return true;
}

} // namespace CompendiumEnrichment
