# CMake generated Testfile for 
# Source directory: /home/solon/Documents/remus/tests
# Build directory: /home/solon/Documents/remus/build-coverage/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ConstantsTest "/home/solon/Documents/remus/build-coverage/tests/test_constants")
set_tests_properties(ConstantsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;16;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(CacheDeserializationTest "/home/solon/Documents/remus/build-coverage/tests/test_cache_deserialization")
set_tests_properties(CacheDeserializationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;26;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SystemNameResolutionTest "/home/solon/Documents/remus/build-coverage/tests/test_system_name_resolution")
set_tests_properties(SystemNameResolutionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;36;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(LevenshteinMatchingTest "/home/solon/Documents/remus/build-coverage/tests/test_levenshtein_matching")
set_tests_properties(LevenshteinMatchingTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;44;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MatchingEngineTest "/home/solon/Documents/remus/build-coverage/tests/test_matching_engine")
set_tests_properties(MatchingEngineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;54;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(DatParserTest "/home/solon/Documents/remus/build-coverage/tests/test_dat_parser")
set_tests_properties(DatParserTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;64;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(TemplateEngineTest "/home/solon/Documents/remus/build-coverage/tests/test_template_engine")
set_tests_properties(TemplateEngineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;75;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MultiFileDetectionTest "/home/solon/Documents/remus/build-coverage/tests/test_multi_file_detection")
set_tests_properties(MultiFileDetectionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;85;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MultiSignalMatchingTest "/home/solon/Documents/remus/build-coverage/tests/test_multi_signal_matching")
set_tests_properties(MultiSignalMatchingTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;95;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(PipelineIntegrationTest "/home/solon/Documents/remus/build-coverage/tests/test_pipeline_integration")
set_tests_properties(PipelineIntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;106;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HasherTest "/home/solon/Documents/remus/build-coverage/tests/test_hasher")
set_tests_properties(HasherTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;116;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HeaderDetectorTest "/home/solon/Documents/remus/build-coverage/tests/test_header_detector")
set_tests_properties(HeaderDetectorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;126;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SystemResolverTest "/home/solon/Documents/remus/build-coverage/tests/test_system_resolver")
set_tests_properties(SystemResolverTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;137;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SettingsControllerTest "/home/solon/Documents/remus/build-coverage/tests/test_settings_controller")
set_tests_properties(SettingsControllerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;147;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(LibraryControllerTest "/home/solon/Documents/remus/build-coverage/tests/test_library_controller")
set_tests_properties(LibraryControllerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;159;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ChdConverterTest "/home/solon/Documents/remus/build-coverage/tests/test_chd_converter")
set_tests_properties(ChdConverterTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;169;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ArchiveExtractorTest "/home/solon/Documents/remus/build-coverage/tests/test_archive_extractor")
set_tests_properties(ArchiveExtractorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;179;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(PatchEngineTest "/home/solon/Documents/remus/build-coverage/tests/test_patch_engine")
set_tests_properties(PatchEngineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;189;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SpaceCalculatorTest "/home/solon/Documents/remus/build-coverage/tests/test_space_calculator")
set_tests_properties(SpaceCalculatorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;199;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(RateLimiterTest "/home/solon/Documents/remus/build-coverage/tests/test_rate_limiter")
set_tests_properties(RateLimiterTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;210;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MetadataProviderTest "/home/solon/Documents/remus/build-coverage/tests/test_metadata_provider")
set_tests_properties(MetadataProviderTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;222;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HasheousParsingTest "/home/solon/Documents/remus/build-coverage/tests/test_hasheous_parsing")
set_tests_properties(HasheousParsingTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;233;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(FilenameNormalizerTest "/home/solon/Documents/remus/build-coverage/tests/test_filename_normalizer")
set_tests_properties(FilenameNormalizerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;243;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MetadataCacheTest "/home/solon/Documents/remus/build-coverage/tests/test_metadata_cache")
set_tests_properties(MetadataCacheTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;255;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ProviderOrchestratorTest "/home/solon/Documents/remus/build-coverage/tests/test_provider_orchestrator")
set_tests_properties(ProviderOrchestratorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;266;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HashAlgorithmsTest "/home/solon/Documents/remus/build-coverage/tests/test_hash_algorithms")
set_tests_properties(HashAlgorithmsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;276;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ScannerTest "/home/solon/Documents/remus/build-coverage/tests/test_scanner")
set_tests_properties(ScannerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;286;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ArtworkDownloaderTest "/home/solon/Documents/remus/build-coverage/tests/test_artwork_downloader")
set_tests_properties(ArtworkDownloaderTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;298;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ProvidersMinimalTest "/home/solon/Documents/remus/build-coverage/tests/test_providers_minimal")
set_tests_properties(ProvidersMinimalTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;309;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(CliSmokeTest "/home/solon/Documents/remus/build-coverage/tests/test_cli_smoke")
set_tests_properties(CliSmokeTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;320;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SessionStateTest "/home/solon/Documents/remus/build-coverage/tests/test_session_state")
set_tests_properties(SessionStateTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;334;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ThemeConstantsTest "/home/solon/Documents/remus/build-coverage/tests/test_theme_constants")
set_tests_properties(ThemeConstantsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;345;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(DatManagerControllerTest "/home/solon/Documents/remus/build-coverage/tests/test_dat_manager_controller")
set_tests_properties(DatManagerControllerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;355;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(TuiWidgetsTest "/home/solon/Documents/remus/build-coverage/tests/test_tui_widgets")
set_tests_properties(TuiWidgetsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;364;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(LibraryScreenTest "/home/solon/Documents/remus/build-coverage/tests/test_library_screen")
set_tests_properties(LibraryScreenTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;373;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(TuiPipelineTest "/home/solon/Documents/remus/build-coverage/tests/test_tui_pipeline")
set_tests_properties(TuiPipelineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;382;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MatchScreenTest "/home/solon/Documents/remus/build-coverage/tests/test_match_screen")
set_tests_properties(MatchScreenTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;391;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(CompressorScreenTest "/home/solon/Documents/remus/build-coverage/tests/test_compressor_screen")
set_tests_properties(CompressorScreenTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;400;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(PatchScreenTest "/home/solon/Documents/remus/build-coverage/tests/test_patch_screen")
set_tests_properties(PatchScreenTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;409;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(OptionsScreenTest "/home/solon/Documents/remus/build-coverage/tests/test_options_screen")
set_tests_properties(OptionsScreenTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;418;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ToolHintsTest "/home/solon/Documents/remus/build-coverage/tests/test_tool_hints")
set_tests_properties(ToolHintsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;426;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(LibraryServiceTest "/home/solon/Documents/remus/build-coverage/tests/test_library_service")
set_tests_properties(LibraryServiceTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;439;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MatchServiceTest "/home/solon/Documents/remus/build-coverage/tests/test_match_service")
set_tests_properties(MatchServiceTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;449;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ConversionServiceTest "/home/solon/Documents/remus/build-coverage/tests/test_conversion_service")
set_tests_properties(ConversionServiceTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;458;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(PatchServiceTest "/home/solon/Documents/remus/build-coverage/tests/test_patch_service")
set_tests_properties(PatchServiceTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;467;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HashServiceTest "/home/solon/Documents/remus/build-coverage/tests/test_hash_service")
set_tests_properties(HashServiceTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;477;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
