# CMake generated Testfile for 
# Source directory: /home/solon/Documents/remus/tests
# Build directory: /home/solon/Documents/remus/build-coverage/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ConstantsTest "/home/solon/Documents/remus/build-coverage/tests/test_constants")
set_tests_properties(ConstantsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;15;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(CacheDeserializationTest "/home/solon/Documents/remus/build-coverage/tests/test_cache_deserialization")
set_tests_properties(CacheDeserializationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;25;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SystemNameResolutionTest "/home/solon/Documents/remus/build-coverage/tests/test_system_name_resolution")
set_tests_properties(SystemNameResolutionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;35;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(LevenshteinMatchingTest "/home/solon/Documents/remus/build-coverage/tests/test_levenshtein_matching")
set_tests_properties(LevenshteinMatchingTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;43;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MatchingEngineTest "/home/solon/Documents/remus/build-coverage/tests/test_matching_engine")
set_tests_properties(MatchingEngineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;53;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(DatParserTest "/home/solon/Documents/remus/build-coverage/tests/test_dat_parser")
set_tests_properties(DatParserTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;63;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(TemplateEngineTest "/home/solon/Documents/remus/build-coverage/tests/test_template_engine")
set_tests_properties(TemplateEngineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;74;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MultiFileDetectionTest "/home/solon/Documents/remus/build-coverage/tests/test_multi_file_detection")
set_tests_properties(MultiFileDetectionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;84;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MultiSignalMatchingTest "/home/solon/Documents/remus/build-coverage/tests/test_multi_signal_matching")
set_tests_properties(MultiSignalMatchingTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;94;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(PipelineIntegrationTest "/home/solon/Documents/remus/build-coverage/tests/test_pipeline_integration")
set_tests_properties(PipelineIntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;105;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HasherTest "/home/solon/Documents/remus/build-coverage/tests/test_hasher")
set_tests_properties(HasherTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;115;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HeaderDetectorTest "/home/solon/Documents/remus/build-coverage/tests/test_header_detector")
set_tests_properties(HeaderDetectorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;125;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SystemResolverTest "/home/solon/Documents/remus/build-coverage/tests/test_system_resolver")
set_tests_properties(SystemResolverTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;136;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SettingsControllerTest "/home/solon/Documents/remus/build-coverage/tests/test_settings_controller")
set_tests_properties(SettingsControllerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;146;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(LibraryControllerTest "/home/solon/Documents/remus/build-coverage/tests/test_library_controller")
set_tests_properties(LibraryControllerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;158;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ChdConverterTest "/home/solon/Documents/remus/build-coverage/tests/test_chd_converter")
set_tests_properties(ChdConverterTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;168;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ArchiveExtractorTest "/home/solon/Documents/remus/build-coverage/tests/test_archive_extractor")
set_tests_properties(ArchiveExtractorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;178;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(PatchEngineTest "/home/solon/Documents/remus/build-coverage/tests/test_patch_engine")
set_tests_properties(PatchEngineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;188;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(SpaceCalculatorTest "/home/solon/Documents/remus/build-coverage/tests/test_space_calculator")
set_tests_properties(SpaceCalculatorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;198;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(RateLimiterTest "/home/solon/Documents/remus/build-coverage/tests/test_rate_limiter")
set_tests_properties(RateLimiterTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;209;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MetadataProviderTest "/home/solon/Documents/remus/build-coverage/tests/test_metadata_provider")
set_tests_properties(MetadataProviderTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;221;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(MetadataCacheTest "/home/solon/Documents/remus/build-coverage/tests/test_metadata_cache")
set_tests_properties(MetadataCacheTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;233;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ProviderOrchestratorTest "/home/solon/Documents/remus/build-coverage/tests/test_provider_orchestrator")
set_tests_properties(ProviderOrchestratorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;244;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(HashAlgorithmsTest "/home/solon/Documents/remus/build-coverage/tests/test_hash_algorithms")
set_tests_properties(HashAlgorithmsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;254;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ScannerTest "/home/solon/Documents/remus/build-coverage/tests/test_scanner")
set_tests_properties(ScannerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;264;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ArtworkDownloaderTest "/home/solon/Documents/remus/build-coverage/tests/test_artwork_downloader")
set_tests_properties(ArtworkDownloaderTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;276;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ProvidersMinimalTest "/home/solon/Documents/remus/build-coverage/tests/test_providers_minimal")
set_tests_properties(ProvidersMinimalTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;287;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(ThemeConstantsTest "/home/solon/Documents/remus/build-coverage/tests/test_theme_constants")
set_tests_properties(ThemeConstantsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;298;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
add_test(DatManagerControllerTest "/home/solon/Documents/remus/build-coverage/tests/test_dat_manager_controller")
set_tests_properties(DatManagerControllerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/solon/Documents/remus/tests/CMakeLists.txt;308;add_test;/home/solon/Documents/remus/tests/CMakeLists.txt;0;")
