#ifndef REMUS_LOGGING_CATEGORIES_H
#define REMUS_LOGGING_CATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCore)
Q_DECLARE_LOGGING_CATEGORY(logMetadata)
Q_DECLARE_LOGGING_CATEGORY(logUi)
Q_DECLARE_LOGGING_CATEGORY(logCli)

#endif // REMUS_LOGGING_CATEGORIES_H
